/**
 * Ethiopian Prompts, System Contexts, Personas, and UI Translations
 * Provides culturally rich presets and multilingual interface texts.
 */

export const SYSTEM_PROMPTS = {
    general: `You are "Selam AI" (ሰላም AI) — an intelligent, polite, warm, and highly knowledgeable Ethiopian AI Assistant and companion.
Key Guidelines:
1. Multilingual Fluency: You are completely fluent in Amharic (አማርኛ), English, Afaan Oromoo, and Tigrinya (ትግርኛ). Always respond in the language or script the user chooses to speak in, or switch gracefully when asked.
2. Cultural Knowledge: You have deep and respectful expertise in Ethiopian culture, ancient and modern history (such as the Victory of Adwa, Axum, Lalibela rock-hewn churches, Gondar castles, Harar Jugol, Tiya), traditional coffee ceremonies (Abol, Tona, Baraka), holidays (Enkutatash, Meskel, Timkat, Genna, Irreecha, Eid), cuisines (Injera, Doro Wat, Shiro, Kitfo, Beyaynetu), and the unique Ethiopian 13-month calendar.
3. Modern Context: You understand contemporary Ethiopian life, geography (Addis Ababa, Hawassa, Bahir Dar, Mekelle, Dire Dawa, Jimma), economy, fintech (Telebirr, CBE Birr, Chapa), public transport, and the thriving tech community.
4. Helpful & Educational: You provide clear, concise, well-structured, formatted responses with Markdown (headers, bullet points, bold text, code blocks).
5. Tone: Respectful, uplifting, encouraging, culturally grounded yet globally intelligent. Greet people warmly (e.g. "ሰላም!", "እንደምን አደርክ/አመሸህ!", "Akkam!", "ሰላም ከመይ ኣለኻ!").`,

    scholar: `You are "Professor Yared" (ፕሮፌሰር ያሬድ) — an esteemed Ethiopian historian, cultural anthropologist, and scholar.
Provide deep, historically verified insights into Ethiopian archaeology, manuscripts, Ge'ez heritage, royal dynasties, the Battle of Adwa, battle strategies, indigenous knowledge systems, and African unity. Write in an articulate, academic, yet accessible style in Amharic and English.`,

    tutor: `You are "Tech Habesha" (ቴክ ሀበሻ) — a friendly software engineering and science mentor for Ethiopian students.
You explain coding concepts (JavaScript, Python, HTML/CSS, Web Dev, Algorithms) in simple, encouraging terms with relatable Ethiopian analogies and clear code snippets. You assist Hiruy students and Ethiopian learners in mastering computer science and modern technologies.`,

    tourism: `You are "Abyssinia Explorer" (አቢሲኒያ አስጎብኚ) — an energetic, inspiring Ethiopian tour guide.
You know every corner of Ethiopia: from the Simien Mountains and Danakil Depression to the Bale Mountains, Lake Tana monasteries, Omo Valley, and vibrant Addis Ababa cafes. You provide travel itineraries, packing tips, cultural etiquette, and hidden gems.`,
};

export const PROMPT_CATEGORIES = [
    {
        id: "coffee",
        icon: "☕",
        titleAm: "የቡና ሥነ-ስርዓት",
        titleEn: "Coffee Ceremony",
        promptAm: "ስለ ኢትዮጵያ የቡና ሥነ-ስርዓት፣ አመጣጡ እና ሦስቱ ዙሮች (አቦል፣ ቶና፣ በረካ) ዝርዝር ማብራሪያ ስጠኝ።",
        promptEn: "Explain the Ethiopian traditional coffee ceremony, its origins, and the meaning of Abol, Tona, and Baraka.",
    },
    {
        id: "adwa",
        icon: "⚔️",
        titleAm: "የአድዋ ድል ታሪክ",
        titleEn: "Victory of Adwa",
        promptAm: "ስለ ታላቁ የአድዋ ድል፣ የዳግማዊ አፄ ምኒልክና የእቴጌ ጣይቱ ሚና፣ እንዲሁም ለአፍሪካና ለዓለም ጥቁር ህዝቦች የነበረውን ፋይዳ በአጭሩ አስረዳኝ።",
        promptEn: "Summarize the 1896 Battle of Adwa, the leadership of Emperor Menelik II and Empress Taytu, and its global significance for pan-Africanism.",
    },
    {
        id: "calendar",
        icon: "📅",
        titleAm: "የቀን አቆጣጠር ልዩነት",
        titleEn: "Ethiopian Calendar",
        promptAm: "የኢትዮጵያ የቀን መቁጠሪያ ከጎርጎሮሳውያን (Gregorian) ካላንደር በምን በምን ይለያል? ለምንስ የ7 ወይም 8 ዓመታት ልዩነት አለው?",
        promptEn: "How does the Ethiopian Calendar differ from the Gregorian calendar, and why is it 7 to 8 years behind?",
    },
    {
        id: "recipe",
        icon: "🍲",
        titleAm: "የዶሮ ወጥ አሰራር",
        titleEn: "Doro Wat Recipe",
        promptAm: "ትክክለኛውን ባህላዊ የኢትዮጵያ የዶሮ ወጥ አሰራር ከሚያስፈልጉ ቅመማ ቅመሞች ጋር ደረጃ በደረጃ ንገረኝ።",
        promptEn: "Give me the step-by-step authentic recipe for traditional Ethiopian Doro Wat with Berbere and Niter Kibbeh.",
    },
    {
        id: "coding",
        icon: "💻",
        titleAm: "የኮዲንግ ትምህርት",
        titleEn: "Learn Programming",
        promptAm: "ለጀማሪ የኮምፒውተር ሳይንስ ተማሪ የJavaScript loop እና function ምንነት በአማርኛ ምሳሌዎችን በመጠቀም ግልጽ አድርገህ አስተምረኝ።",
        promptEn: "Explain JavaScript functions and loops for a beginner student using simple relatable analogies and code examples.",
    },
    {
        id: "tourism",
        icon: "🏰",
        titleAm: "የኢትዮጵያ ቅርሶች",
        titleEn: "Historical Wonders",
        promptAm: "በኢትዮጵያ ውስጥ የሚገኙ ዋና ዋና የዩኔስኮ የዓለም ቅርሶች (እንደ ላሊበላ፣ ፋሲል ግቢ፣ አክሱም) እና ለምን መጎብኘት እንዳለባቸው አብራራልኝ።",
        promptEn: "What are the top UNESCO World Heritage sites in Ethiopia (like Lalibela, Fasil Ghebbi, Axum) and why should people visit them?",
    },
];

export const UI_TRANSLATIONS = {
    am: {
        appTitle: "ሰላም AI",
        tagline: "የኢትዮጵያ ብልህ ረዳት",
        newChat: "አዲስ ጭውውት",
        chatHistory: "የቀደሙ ጭውውቶች",
        noHistory: "ምንም የቀደመ ጭውውት የለም",
        emptyHeroTitle: "ሰላም! ዛሬ ምን ላግዝዎ?",
        emptyHeroSubtitle: "በቋንቋዎ ይጠይቁ — ታሪክ፣ ባህል፣ ትምህርት፣ ቴክኖሎጂ እና ሌሎችንም አብረን እንመርምር።",
        placeholder: "ጥያቄዎን በአማርኛ ወይም በእንግሊዝኛ እዚህ ይጻፉ...",
        send: "ላክ",
        calendarBadge: "የዛሬ ቀን",
        convertDate: "ቀን ቀይር",
        settings: "ቅንብሮች",
        clearChat: "ውይይት አጽዳ",
        exportChat: "ውይይት አውርድ",
        voiceListening: "እያዳመጥኩ ነው... ይናገሩ",
        voiceStart: "በድምፅ ለመጠየቅ ይጫኑ",
        thinking: "ሰላም AI እያሰበ ነው...",
        copyMessage: "መልዕክቱን ገልብጥ",
        copied: "ተገልብጧል!",
        readAloud: "በድምፅ አንብብ",
        speaking: "በማንበብ ላይ...",
        charCount: "ቁምፊዎች",
        confirmClear: "እርግጠኛ ነዎት ውይይቱን ማጽዳት ይፈልጋሉ?",
        cancel: "ተመለስ",
        confirm: "አዎ፣ አጽዳ",
        modelSelection: "የ AI ሞዴል",
        personaSelection: "የ AI ባሕሪ / አቀራረብ",
        apiKeyOverride: "የራስዎን Groq API Key ያስገቡ (አማራጭ)",
        saveSettings: "አስቀምጥ",
        dateConverterTitle: "የቀን መቀየሪያ (Gregorian ⇄ Ethiopian)",
        convertToEth: "ወደ ኢትዮጵያ ቀን ቀይር",
        convertToGreg: "ወደ ጎርጎሮሳውያን ቀን ቀይር",
    },
    en: {
        appTitle: "Selam AI",
        tagline: "Ethiopia's Smart AI Companion",
        newChat: "New Chat",
        chatHistory: "Chat History",
        noHistory: "No past conversations yet",
        emptyHeroTitle: "Selam! How can I help you today?",
        emptyHeroSubtitle: "Ask me anything in Amharic or English — history, culture, programming, and everyday advice.",
        placeholder: "Ask something in Amharic, English, or any language...",
        send: "Send",
        calendarBadge: "Today's Date",
        convertDate: "Convert Date",
        settings: "Settings",
        clearChat: "Clear Chat",
        exportChat: "Export Chat",
        voiceListening: "Listening... speak now",
        voiceStart: "Click to speak voice input",
        thinking: "Selam AI is thinking...",
        copyMessage: "Copy message",
        copied: "Copied!",
        readAloud: "Read aloud",
        speaking: "Reading...",
        charCount: "characters",
        confirmClear: "Are you sure you want to clear this conversation?",
        cancel: "Cancel",
        confirm: "Yes, Clear",
        modelSelection: "AI Model",
        personaSelection: "AI Persona / Tone",
        apiKeyOverride: "Custom Groq API Key (Optional)",
        saveSettings: "Save Settings",
        dateConverterTitle: "Date Converter (Gregorian ⇄ Ethiopian)",
        convertToEth: "Convert to Ethiopian Date",
        convertToGreg: "Convert to Gregorian Date",
    },
    om: {
        appTitle: "Selam AI",
        tagline: "Gargaaraa AI Itoophiyaa",
        newChat: "Haasaa Haaraa",
        chatHistory: "Seenaa Haasaa",
        noHistory: "Haasofni darbe hin jiru",
        emptyHeroTitle: "Akkam! Har'a maal si gargaaruu?",
        emptyHeroSubtitle: "Afaan Oromootiin ykn Ingiliffaan na gaafadhaa — seenaa, aadaa, barumsa fi teeknooloojii.",
        placeholder: "Gaaffii keessan asitti barreessaa...",
        send: "Ergi",
        calendarBadge: "Guyyaa Har'aa",
        convertDate: "Guyyaa Jijjiiri",
        settings: "Qindaa'ina",
        clearChat: "Haasaa Haxaa'i",
        exportChat: "Haasaa Buusi",
        voiceListening: "Dhaggeeffachaan jira... dubbadhaa",
        voiceStart: "Sagaleen gaafachuuf cuqaasaa",
        thinking: "Selam AI yaadaa jira...",
        copyMessage: "Waraabi",
        copied: "Waraabameera!",
        readAloud: "Sagaleen dubbisi",
        speaking: "Dubbisaa jira...",
        charCount: "qubeewwan",
        confirmClear: "Haasaa kana balleessuu barbaadduu?",
        cancel: "Dhiisi",
        confirm: "Eeyyee, Balleessi",
        modelSelection: "Moodeela AI",
        personaSelection: "Amala AI",
        apiKeyOverride: "Groq API Key keessan (Filannoo)",
        saveSettings: "Olkaawi",
        dateConverterTitle: "Guyyaa Jijjiirraa (Gregorian ⇄ Itoophiyaa)",
        convertToEth: "Gara Guyyaa Itoophiyaatti",
        convertToGreg: "Gara Guyyaa Gregorianitti",
    },
    ti: {
        appTitle: "ሰላም AI",
        tagline: "ናይ ኢትዮጵያ ብልሒ ሓጋዚ",
        newChat: "ሓድሽ ምይይጥ",
        chatHistory: "ዝሓለፉ ምይይጣት",
        noHistory: "ዝኾነ ዝሓለፈ ምይይጥ የለን",
        emptyHeroTitle: "ሰላም! ሎሚ ብምንታይ ክሕግዘካ?",
        emptyHeroSubtitle: "ብትግርኛ ወይ ብእንግሊዝኛ ሕተት — ታሪኽ፣ ባህሊ፣ ትምህርቲ፣ ቴክኖሎጂን ካልኦትን።",
        placeholder: "ሕቶኻ ብትግርኛ ወይ ብእንግሊዝኛ ኣብዚ ጸሓፍ...",
        send: "ስደድ",
        calendarBadge: "ናይ ሎሚ ዕለት",
        convertDate: "ዕለት ቀይር",
        settings: "ቅጥዕታት",
        clearChat: "ምይይጥ ኣጽሪ",
        exportChat: "ምይይጥ ኣውርድ",
        voiceListening: "ይሰምዕ ኣለኹ... ተዛረብ",
        voiceStart: "ብድምጺ ንምሕታት ጠውቕ",
        thinking: "ሰላም AI ይሓስብ ኣሎ...",
        copyMessage: "መልእኽቲ ቅዳሕ",
        copied: "ተቐዲሑ!",
        readAloud: "ብድምጺ ኣንብብ",
        speaking: "የንብብ ኣሎ...",
        charCount: "ፊደላት",
        confirmClear: "ነዚ ምይይጥ ከተጽርዮ ርግጸኛ ዲኻ?",
        cancel: "ተመለስ",
        confirm: "እወ፣ ኣጽሪ",
        modelSelection: "ናይ AI ሞዴል",
        personaSelection: "ናይ AI ባህሪ",
        apiKeyOverride: "ናይ ውልቀኻ Groq API Key (ምርጫ)",
        saveSettings: "ኣቐምጥ",
        dateConverterTitle: "መቐየሪ ዕለት (Gregorian ⇄ ናይ ኢትዮጵያ)",
        convertToEth: "ናብ ናይ ኢትዮጵያ ዕለት ቀይር",
        convertToGreg: "ናብ ጎርጎሮሳውያን ዕለት ቀይር",
    },
};
